name: Scheduled Ping
on:
  schedule:
    - cron:  '*/30 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pinger_job:
    name: A job to ping
    runs-on: ubuntu-latest
    env:
      URL: ${{ www.willingbikes.com }}
      METHOD: GET 
    steps:
      - id: ping
        uses: sisodiya2421/pinger@master
